# Generated by Django 3.1.2 on 2020-10-30 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('answer', models.CharField(max_length=300)),
                ('status', models.IntegerField()),
                ('era_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.era')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.level')),
            ],
        ),
    ]
